const DEFAULT_USERS={Alessandro:{password:null,preferiti:[],visti:[],valutazioni:{},record_gioco:0,achievement_sbloccati:[]},Giuliana:{password:null,preferiti:[],visti:[],valutazioni:{},record_gioco:0,achievement_sbloccati:[]}};
let films={},users={},currentUser=null,selectedFilm=null,screen='login',game=null;
const EXCLUSIVE='⭐ FILM ESCLUSIVO - Sorpresa di Compleanno! 🎁';
const ACH=[['primo_passo','Primo passo','Guarda il primo film','🥉',d=>d.visti.length>=1],['maratoneta','Maratoneta','Guarda 10 film','🥈',d=>d.visti.length>=10],['archivista','Archivista Marvel','Guarda 25 film','🥇',d=>d.visti.length>=25],['fan_assoluto','Fan assoluto','Aggiungi 15 preferiti','❤️',d=>d.preferiti.length>=15],['critico','Critico cinematografico','Vota 20 film','⭐',d=>Object.keys(d.valutazioni).length>=20],['spider_verse','Spider-Verse','Guarda tutti gli Spider-Man','🕷️',d=>['Spider-Man (2002)','Spider-Man 2 (2004)','Spider-Man 3 (2007)','The Amazing Spider-Man (2012)','The Amazing Spider-Man 2 (2014)','Spider-Man: Homecoming (2017)','Spider-Man: Far from Home (2019)','Spider-Man: No Way Home (2021)'].every(f=>d.visti.includes(f))],['avenger','Avenger','Completa tutte le Fasi 1–3','⚡',d=>Object.entries(films).filter(([_,x])=>['MCU Fase 1','MCU Fase 2','MCU Fase 3'].includes(x.fase)).every(([f])=>d.visti.includes(f))],['sopravvissuto','Sopravvissuto al Multiverso','Raggiungi 500 punti nel gioco','💀',d=>d.record_gioco>=500],['collezionista','Collezionista','Aggiungi 5 preferiti','💎',d=>d.preferiti.length>=5],['cinefilo','Cinefilo','Guarda 50 film','🎬',d=>d.visti.length>=50],['cinque_stelle','Cinque stelle','Dai almeno una valutazione da 5 stelle','🌟',d=>Object.values(d.valutazioni).includes(5)],['multiverso','Esploratore del Multiverso','Guarda film di 5 universi differenti','🌌',d=>new Set(d.visti.filter(f=>films[f]).map(f=>films[f].fase)).size>=5],['campione','Campione dell’arena','Raggiungi 1000 punti','🏆',d=>d.record_gioco>=1000],['legendario','Leggendario','Guarda 75 film','👑',d=>d.visti.length>=75],['completista','Completista','Guarda tutto il catalogo','🔥',d=>d.visti.length>=Object.keys(films).length]];
function load(){films=window.__FILMS||{}; const raw=localStorage.getItem('marvel_experience_users'); users=raw?JSON.parse(raw):structuredClone(DEFAULT_USERS); for(const n in DEFAULT_USERS) users[n] ||= structuredClone(DEFAULT_USERS[n]);}
async function boot(){
  const loadFilms = fetch('./films.json?cacheBust='+Date.now(), {cache:'no-store'})
    .then(r => { if(!r.ok) throw new Error('Catalogo non disponibile'); return r.json(); })
    .then(data => { films = data || {}; })
    .catch(() => { films = {}; });
  const timeout = new Promise(resolve => setTimeout(resolve, 2500));
  await Promise.race([loadFilms, timeout]);
  try {
    const raw=localStorage.getItem('marvel_experience_users');
    users=raw?JSON.parse(raw):structuredClone(DEFAULT_USERS);
  } catch(e) {
    users=structuredClone(DEFAULT_USERS);
  }
  Object.keys(DEFAULT_USERS).forEach(n=>users[n] ||= structuredClone(DEFAULT_USERS[n]));
  document.getElementById('splash').classList.add('hide');
  render();
  loadFilms.then(()=>{ if(Object.keys(films).length && screen!=='login') render(); });
}
function save(){localStorage.setItem('marvel_experience_users',JSON.stringify(users))} function d(){return users[currentUser]}
function unlocked(){return ACH.filter(a=>a[4](d())).map(a=>a[0])} function checkAchievements(){const u=d();const before=new Set(u.achievement_sbloccati||[]);const now=unlocked();u.achievement_sbloccati=now;save();const fresh=now.filter(x=>!before.has(x));if(fresh.length) toast('🏆 Achievement sbloccato!')}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function go(s){screen=s;render()}
function top(title,back='home'){return `<div class="topbar"><button class="btn secondary" onclick="go('${back}')">←</button><h2>${title}</h2></div>`}
function render(){const a=document.getElementById('app'); if(screen==='login')a.innerHTML=login(); else if(screen==='home')a.innerHTML=home(); else if(screen==='cinema')a.innerHTML=cinema(); else if(screen==='detail')a.innerHTML=detail(); else if(screen==='profile')a.innerHTML=profile(); else if(screen==='ach')a.innerHTML=achievements(); else if(screen==='game')a.innerHTML=gameScreen();}
function login(){return `<section class="screen active"><div class="wrap"><div class="hero"><div class="logo">🦸‍♂️</div><h1>MARVEL EXPERIENCE</h1><p>Il tuo universo. Le tue regole.</p></div><div class="login-grid"><div class="card"><h3>Scegli il profilo</h3><div class="profile-select">${Object.keys(users).map(n=>`<button class="profile-btn" onclick="selectUser('${n}')">👤 ${n}</button>`).join('')}</div><div class="install-note">📱 Dopo aver pubblicato questa cartella, dal telefono potrai aggiungere l'app alla schermata Home: resterà installata come una vera app.</div></div></div></div></section>`}
function selectUser(n){currentUser=n;if(users[n].password){const p=prompt('Inserisci la password');if(p!==users[n].password){toast('Password errata');return}};go('home')}
function home(){checkAchievements();const u=d(),total=Object.keys(films).length;return `<section class="screen active"><div class="wrap"><div class="hero"><div class="logo">🕷️</div><h1>BENVENUTA/O ${currentUser.toUpperCase()}</h1><p>🍿 ${u.visti.length}/${total} film visti · ❤️ ${u.preferiti.length} preferiti · 🏆 ${u.achievement_sbloccati.length}/${ACH.length} achievement · 🎮 Record: ${u.record_gioco}</p></div><div class="cards"><div class="card action" onclick="go('cinema')"><div class="ico">🎬</div><h3>CINEMA</h3><p>Esplora Marvel, Spider-Man, preferiti, trailer e molto altro.</p></div><div class="card action" onclick="go('game')"><div class="ico">🎮</div><h3>GIOCHI</h3><p>Entra nell'arena e prova a battere il tuo record.</p></div><div class="card action" onclick="go('profile')"><div class="ico">📊</div><h3>IL MIO PROFILO</h3><p>Statistiche, personaggio preferito e fase preferita.</p></div><div class="card action" onclick="go('ach')"><div class="ico">🏆</div><h3>ACHIEVEMENT</h3><p>${u.achievement_sbloccati.length}/${ACH.length} sbloccati.</p></div></div><div style="margin-top:14px;text-align:center"><button class="btn secondary" onclick="changePassword()">🔐 Cambia password</button> <button class="btn secondary" onclick="currentUser=null;go('login')">🚪 Cambia utente</button></div></div></section>`}
function changePassword(){const p=prompt('Nuova password (lascia vuoto per rimuoverla)');if(p===null)return;d().password=p||null;save();toast('Password aggiornata')}
function cinema(){const q=window.cq||'';const phase=window.cp||'Tutte le Fasi';const order=window.co||'Anno (Crescente)';let arr=Object.entries(films).filter(([t,x])=>(!q||t.toLowerCase().includes(q.toLowerCase()))&&(phase==='Tutte le Fasi'||(phase==='❤️ Preferiti'?d().preferiti.includes(t):x.fase===phase)));arr.sort((a,b)=>order==='Titolo (A-Z)'?a[0].localeCompare(b[0]):order==='Anno (Decrescente)'?b[1].anno-a[1].anno:a[1].anno-b[1].anno);return `<section class="screen active">${top('MARVEL EXPERIENCE')}<div class="wrap"><input class="input search" placeholder="🔍 Cerca film..." value="${esc(q)}" oninput="window.cq=this.value;render()"><div class="filters"><select class="select" onchange="window.cp=this.value;render()"><option>Tutte le Fasi</option><option>❤️ Preferiti</option>${[1,2,3,4,5].map(n=>`<option>MCU Fase ${n}</option>`).join('')}<option>Trilogia Raimi</option><option>The Amazing Spider-Man</option><option>Sony's Spider-Man Universe</option><option>Edizione Speciale 🎁</option></select><select class="select" onchange="window.co=this.value;render()"><option>Anno (Crescente)</option><option>Anno (Decrescente)</option><option>Titolo (A-Z)</option></select></div><div class="section-title"><h3>Catalogo</h3><span class="muted">${arr.length} risultati</span></div><div class="film-list">${arr.map(([t,x])=>`<div class="film-item" onclick="openFilm(${JSON.stringify(t)})"><div class="film-icon">🎬</div><div><h4>${esc(t)}</h4><p>${esc(x.fase)} · ${x.anno} · ${esc(x.durata)}</p></div><div class="badge">${d().visti.includes(t)?'✅':d().preferiti.includes(t)?'❤️':''}</div></div>`).join('')}</div></div></section>`}
function openFilm(t){selectedFilm=t;go('detail')}
function detail(){const t=selectedFilm,x=films[t],u=d(),v=u.valutazioni[t]||0;return `<section class="screen active">${top('DETTAGLI','cinema')}<div class="wrap"><div class="detail"><div class="film-icon" style="width:60px;height:76px;font-size:30px">🎬</div><h1>${esc(t)}</h1><div class="meta"><b>${esc(x.fase)}</b> · ${x.anno} · ${esc(x.durata)}<br>Regia: ${esc(x.regia)}<br>Cast: ${esc(x.cast)}</div><p class="plot">${esc(x.trama)}</p><div class="row"><button class="btn ${u.visti.includes(t)?'secondary':''}" onclick="toggleVisto()">${u.visti.includes(t)?'✅ VISTO':'☑️ SEGNA COME VISTO'}</button><button class="btn ${u.preferiti.includes(t)?'secondary':''}" onclick="toggleFav()">${u.preferiti.includes(t)?'❤️ PREFERITO':'♡ AGGIUNGI AI PREFERITI'}</button></div><div class="section-title"><h3>La tua valutazione</h3><span class="muted">${v?`${v}/5`:''}</span></div><div class="stars">${[1,2,3,4,5].map(i=>`<button class="star ${i<=v?'on':''}" onclick="rate(${i})">★</button>`).join('')}</div><div class="row" style="margin-top:14px">${t===EXCLUSIVE?`<button class="btn gold" onclick="openExclusive()">🎁 APRI IL CONTENUTO SPECIALE</button>`:`<button class="btn" onclick="openTrailer()">▶️ CERCA TRAILER</button>`}</div></div></div></section>`}
function toggleVisto(){const u=d(),i=u.visti.indexOf(selectedFilm);i>=0?u.visti.splice(i,1):u.visti.push(selectedFilm);save();checkAchievements();render()}function toggleFav(){const u=d(),i=u.preferiti.indexOf(selectedFilm);i>=0?u.preferiti.splice(i,1):u.preferiti.push(selectedFilm);save();checkAchievements();render()}function rate(n){d().valutazioni[selectedFilm]=n;save();checkAchievements();render()}function openTrailer(){window.open('https://www.youtube.com/results?search_query='+encodeURIComponent(selectedFilm+' trailer ita'),'_blank','noopener')}
function openExclusive(){const url='https://drive.google.com/your-video-link-here';window.open(url,'_blank','noopener')}
function profile(){const u=d(),total=Object.keys(films).length,avg=Object.values(u.valutazioni);const media=avg.length?(avg.reduce((a,b)=>a+b,0)/avg.length).toFixed(1):'—';const phases=u.visti.filter(f=>films[f]).map(f=>films[f].fase);const pf=mostCommon(phases)||'—';const chars={};u.visti.forEach(f=>{const c=(films[f]?.cast||'').split(',')[0];if(c)chars[c]=(chars[c]||0)+1});const pc=mostCommon(Object.keys(chars).sort((a,b)=>chars[b]-chars[a]))||'—';return `<section class="screen active">${top('📊 IL MIO PROFILO')}<div class="wrap"><div class="hero"><h1>PROFILO DI ${currentUser.toUpperCase()}</h1><p>Il tuo universo Marvel personale</p></div><div class="card"><h3>Progresso</h3><div class="progress"><i style="width:${Math.round(u.visti.length/total*100)}%"></i></div><p class="muted">${u.visti.length}/${total} film</p></div><div class="stats" style="margin-top:12px">${stat('🎬','FILM VISTI',`${u.visti.length}/${total}`)}${stat('❤️','PREFERITI',u.preferiti.length)}${stat('⭐','MEDIA VOTI',media+'/5')}${stat('🎮','RECORD',u.record_gioco)}${stat('🏆','ACHIEVEMENT',`${u.achievement_sbloccati.length}/${ACH.length}`)}${stat('⏱️','ORE MARVEL',`${Math.floor(u.visti.length*2/60)}h ${(u.visti.length*2)%60}m`)}${stat('🦸','PERSONAGGIO',pc)}${stat('🎞️','FASE PREFERITA',pf)}</div></div></section>`}
function stat(i,l,v){return `<div class="stat"><div class="i">${i}</div><div class="v">${esc(String(v))}</div><div class="l">${l}</div></div>`}function mostCommon(a){if(!a.length)return null;const c={};a.forEach(x=>c[x]=(c[x]||0)+1);return Object.entries(c).sort((a,b)=>b[1]-a[1])[0][0]}
function achievements(){checkAchievements();const u=d();return `<section class="screen active">${top('🏆 I MIEI ACHIEVEMENT','home')}<div class="wrap"><div class="hero"><h1>${u.achievement_sbloccati.length} / ${ACH.length}</h1><p>ACHIEVEMENT SBLOCCATI · Progresso ${Math.round(u.achievement_sbloccati.length/ACH.length*100)}%</p></div><div class="ach-grid">${ACH.map(a=>{const on=u.achievement_sbloccati.includes(a[0]);return `<div class="ach ${on?'unlocked':''}"><div class="ico">${on?a[3]:'🔒'}</div><h4>${on?a[1]:'Achievement bloccato'}</h4><p>${a[2]}</p></div>`}).join('')}</div></div></section>`}
function gameScreen(){return `<section class="screen active">${top('🎮 MULTIVERSE RUN','home')}<div class="game"><div class="game-canvas" id="gameArea"></div><div class="game-title"><h1>MULTIVERSE RUN</h1><p>Muovi Spider-Man e raccogli i simboli del multiverso!</p></div><div class="hud"><span id="score">PUNTEGGIO: 0</span><span>❤️ <b id="lives">3</b> · RECORD: ${d().record_gioco}</span></div><div id="over" class="gameover"><div><h2>GAME OVER</h2><p id="finalScore"></p><button class="btn" onclick="startGame()">🔄 RIGIOCA</button></div></div><div class="controls"><button class="empty"></button><button data-key="up">↑</button><button class="empty"></button><button data-key="left">←</button><button data-key="down">↓</button><button data-key="right">→</button></div></div></section>`}
function startGame(){const area=document.getElementById('gameArea');if(!area)return;area.innerHTML='';document.getElementById('over').classList.remove('show');game={x:area.clientWidth/2,y:area.clientHeight-90,score:0,lives:3,enemies:[],coins:[],keys:new Set(),run:true,last:performance.now(),spawnE:0,spawnC:0};spawnPlayer();requestAnimationFrame(loop)}
function spawnPlayer(){const area=document.getElementById('gameArea'),p=document.createElement('div');p.className='player';p.textContent='🕷️';p.id='player';area.appendChild(p);position(p,game.x,game.y)}function position(el,x,y){el.style.left=(x-el.offsetWidth/2)+'px';el.style.top=(y-el.offsetHeight/2)+'px'}
function spawn(type){const area=document.getElementById('gameArea'),el=document.createElement('div');el.className=type==='e'?'enemy':'coin';el.textContent=type==='e'?'':'✦';const x=25+Math.random()*(area.clientWidth-50);const obj={el,x,y:-30,speed:type==='e'?3+Math.random()*3:3+Math.random()*2,r:type==='e'?20:13};area.appendChild(el);position(el,x,obj.y);(type==='e'?game.enemies:game.coins).push(obj)}
function hit(a,b){return Math.hypot(a.x-b.x,a.y-b.y)<(28+b.r)}function loop(now){if(!game||!game.run)return;const area=document.getElementById('gameArea'),dt=Math.min(40,now-game.last);game.last=now;const speed=8*dt/16; if(game.keys.has('left'))game.x-=speed;if(game.keys.has('right'))game.x+=speed;if(game.keys.has('up'))game.y-=speed;if(game.keys.has('down'))game.y+=speed;game.x=Math.max(30,Math.min(area.clientWidth-30,game.x));game.y=Math.max(110,Math.min(area.clientHeight-30,game.y));position(document.getElementById('player'),game.x,game.y);game.spawnE-=dt;game.spawnC-=dt;if(game.spawnE<=0){spawn('e');game.spawnE=700+Math.random()*600}if(game.spawnC<=0){spawn('c');game.spawnC=500+Math.random()*500}for(const type of ['enemies','coins']){for(let i=game[type].length-1;i>=0;i--){const o=game[type][i];o.y+=o.speed*dt/16;position(o.el,o.x,o.y);if(hit(game,o)){o.el.remove();game[type].splice(i,1);if(type==='coins'){game.score+=10; if(game.score>d().record_gioco){d().record_gioco=game.score;save();checkAchievements()}}else{game.lives--;if(game.lives<=0)return endGame()}}else if(o.y>area.clientHeight+50){o.el.remove();game[type].splice(i,1)}}}document.getElementById('score').textContent='PUNTEGGIO: '+game.score;document.getElementById('lives').textContent=game.lives;requestAnimationFrame(loop)}
function endGame(){game.run=false;document.getElementById('finalScore').textContent=`Punteggio: ${game.score} · 🏆 Record: ${d().record_gioco}`;document.getElementById('over').classList.add('show')}
window.addEventListener('keydown',e=>{if(!game)return;const m={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down'};if(m[e.key]){game.keys.add(m[e.key]);e.preventDefault()}});window.addEventListener('keyup',e=>{if(!game)return;const m={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'up',w:'up',ArrowDown:'down',s:'down'};if(m[e.key])game.keys.delete(m[e.key])});document.addEventListener('touchstart',e=>{const b=e.target.closest('[data-key]');if(b&&game){game.keys.add(b.dataset.key);e.preventDefault()}},{passive:false});document.addEventListener('touchend',e=>{const b=e.target.closest('[data-key]');if(b&&game)game.keys.delete(b.dataset.key)},{passive:false});
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.selectUser=selectUser;window.go=go;window.openFilm=openFilm;window.toggleVisto=toggleVisto;window.toggleFav=toggleFav;window.rate=rate;window.openTrailer=openTrailer;window.openExclusive=openExclusive;window.changePassword=changePassword;window.startGame=startGame;window.render=render;window.cq='';window.cp='Tutte le Fasi';window.co='Anno (Crescente)';
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});boot();